services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: on-failure
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode_1dn:/hadoop/dfs/name
      - ../data:/data:ro
    environment:
      - CLUSTER_NAME=lab2
      - HDFS_CONF_dfs_replication=1
    env_file:
      - ./hadoop.env
    mem_limit: 1g

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: on-failure
    volumes:
      - hadoop_datanode1_1dn:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HDFS_CONF_dfs_replication=1
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    mem_limit: 1g

  spark:
    build: ./spark
    container_name: spark_app
    volumes:
      - ../spark:/app/spark:ro
      - ../data:/app/data:ro
      - ../results:/app/results
    environment:
      - HADOOP_NAMENODE=namenode:9000
      - SETUP_NAME=1dn
    depends_on:
      - namenode
      - datanode1
    mem_limit: 3g
    command: tail -f /dev/null

volumes:
  hadoop_namenode_1dn:
  hadoop_datanode1_1dn:

networks:
  default:
    name: lab2_1dn
